//! Frozen current-producer field contract; see the native totalwatsed3 package.
use crate::schema::{schema_with_version, VersionInfo};
use arrow_schema::{DataType, Field, Schema};
pub const NAMES: &[&str] = &[
    "year",
    "sim_day_index",
    "julian",
    "month",
    "day_of_month",
    "water_year",
    "runvol",
    "sbrunv",
    "tdet",
    "tdep",
    "seddep_1",
    "seddep_2",
    "seddep_3",
    "seddep_4",
    "seddep_5",
    "sed_del",
    "sed_vol_conc",
    "Area",
    "P",
    "RM",
    "Q",
    "Dp",
    "latqcc",
    "QOFE",
    "Ep",
    "Es",
    "Er",
    "UpStrmQ",
    "SubRIn",
    "Total-Soil Water",
    "SoilWaterTotal",
    "ProfileDepth",
    "ProfilePorosityCap",
    "ProfileFCStore",
    "ProfileWPStore",
    "InterceptionStorage",
    "TSMF",
    "frozwt",
    "Snow-Water",
    "QRain",
    "QSnow",
    "Tile",
    "Irr",
    "Precipitation",
    "Rain+Melt",
    "Percolation",
    "Lateral Flow",
    "Runoff",
    "Transpiration",
    "Evaporation",
    "ET",
    "Interception",
    "Baseflow",
    "Aquifer losses",
    "Reservoir Volume",
    "Streamflow",
    "wind_transport",
    "wind_transport_per_ha",
    "wind_transport_black",
    "wind_transport_black_per_ha",
    "wind_transport_white",
    "wind_transport_white_per_ha",
    "water_transport",
    "water_transport_per_ha",
    "water_transport_black",
    "water_transport_black_per_ha",
    "water_transport_white",
    "water_transport_white_per_ha",
    "ash_transport",
    "ash_transport_per_ha",
    "ash_transport_black",
    "ash_transport_black_per_ha",
    "ash_transport_white",
    "ash_transport_white_per_ha",
    "transportable_ash",
    "transportable_ash_per_ha",
    "ash_vol_conc",
    "sed+ash_vol_conc",
    "ash_black_pct_by_vol",
];
pub fn output_schema(version: &VersionInfo, pandas: Option<&str>) -> Schema {
    let fields=vec![
Field::new("year",DataType::Int16,true).with_metadata([].into()),
Field::new("sim_day_index",DataType::Int32,true).with_metadata([].into()),
Field::new("julian",DataType::Int16,true).with_metadata([].into()),
Field::new("month",DataType::Int8,true).with_metadata([].into()),
Field::new("day_of_month",DataType::Int8,true).with_metadata([].into()),
Field::new("water_year",DataType::Int16,true).with_metadata([].into()),
Field::new("runvol",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Runoff volume".into())].into()),
Field::new("sbrunv",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Subsurface runoff volume".into())].into()),
Field::new("tdet",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Total detachment".into())].into()),
Field::new("tdep",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Total deposition".into())].into()),
Field::new("seddep_1",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Sediment Class 1 deposition".into())].into()),
Field::new("seddep_2",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Sediment Class 2 deposition".into())].into()),
Field::new("seddep_3",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Sediment Class 3 deposition".into())].into()),
Field::new("seddep_4",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Sediment Class 4 deposition".into())].into()),
Field::new("seddep_5",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Sediment Class 5 deposition".into())].into()),
Field::new("sed_del",DataType::Float64,true).with_metadata([("units".into(),"kg".into()), ("description".into(),"Total sediment delivery (sum of class masses)".into())].into()),
Field::new("sed_vol_conc",DataType::Float64,true).with_metadata([("units".into(),"m^3/m^3".into()), ("description".into(),"Total volumetric sediment concentration (solids volume divided by runoff volume)".into())].into()),
Field::new("Area",DataType::Float64,true).with_metadata([("units".into(),"m^2".into()), ("description".into(),"Area that depths apply over".into())].into()),
Field::new("P",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Precipitation volume".into())].into()),
Field::new("RM",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Rainfall+Irrigation+Snowmelt volume".into())].into()),
Field::new("Q",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Daily runoff over effective length volume".into())].into()),
Field::new("Dp",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Deep percolation volume".into())].into()),
Field::new("latqcc",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Lateral subsurface flow volume".into())].into()),
Field::new("QOFE",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Daily runoff scaled to single OFE volume".into())].into()),
Field::new("Ep",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Plant transpiration volume".into())].into()),
Field::new("Es",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Soil evaporation volume".into())].into()),
Field::new("Er",DataType::Float64,true).with_metadata([("units".into(),"m^3".into()), ("description".into(),"Residue evaporation volume".into())].into()),
Field::new("UpStrmQ",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Runon added to OFE depth".into())].into()),
Field::new("SubRIn",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Subsurface runon added to OFE depth".into())].into()),
Field::new("Total-Soil Water",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Unfrozen water in soil profile depth".into())].into()),
Field::new("SoilWaterTotal",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted full-profile soil water depth (watcon + frozwt)".into())].into()),
Field::new("ProfileDepth",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted full soil profile depth (solthk(nsl))".into())].into()),
Field::new("ProfilePorosityCap",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted full-profile porosity storage capacity (sum(por * dg))".into())].into()),
Field::new("ProfileFCStore",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted full-profile field-capacity storage (sum(thetfc * dg))".into())].into()),
Field::new("ProfileWPStore",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted full-profile wilting-point storage (sum(thetdr * dg))".into())].into()),
Field::new("InterceptionStorage",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted plant/residue interception carryover storage depth (pintlv + resint)".into())].into()),
Field::new("TSMF",DataType::Float64,true).with_metadata([("units".into(),"frac".into()), ("description".into(),"Area-weighted true soil moisture fraction (full profile)".into())].into()),
Field::new("frozwt",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Frozen water in soil profile depth".into())].into()),
Field::new("Snow-Water",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Water in surface snow depth".into())].into()),
Field::new("QRain",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted rain-generated runoff depth from element partitioning".into())].into()),
Field::new("QSnow",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Area-weighted snow-generated runoff depth from element partitioning".into())].into()),
Field::new("Tile",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Tile drainage depth".into())].into()),
Field::new("Irr",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Irrigation depth".into())].into()),
Field::new("Precipitation",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Precipitation depth".into())].into()),
Field::new("Rain+Melt",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Rainfall+Irrigation+Snowmelt depth".into())].into()),
Field::new("Percolation",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Deep percolation depth".into())].into()),
Field::new("Lateral Flow",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Lateral subsurface flow depth".into())].into()),
Field::new("Runoff",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Daily runoff depth from PASS runoff volume".into())].into()),
Field::new("Transpiration",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Plant transpiration depth".into())].into()),
Field::new("Evaporation",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Soil + residue evaporation depth".into())].into()),
Field::new("ET",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Total evapotranspiration depth".into())].into()),
Field::new("Interception",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Daily canopy/residue interception flux depth (optional producer-authoritative outflow)".into())].into()),
Field::new("Baseflow",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Baseflow depth".into())].into()),
Field::new("Aquifer losses",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Aquifer losses depth".into())].into()),
Field::new("Reservoir Volume",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Groundwater storage depth".into())].into()),
Field::new("Streamflow",DataType::Float64,true).with_metadata([("units".into(),"mm".into()), ("description".into(),"Streamflow depth".into())].into()),
Field::new("wind_transport",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"Ash transported by wind (total mass)".into())].into()),
Field::new("wind_transport_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"Ash transported by wind per unit area".into())].into()),
Field::new("wind_transport_black",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"Black ash transported by wind (total mass)".into())].into()),
Field::new("wind_transport_black_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"Black ash transported by wind per unit area over black ash hillslopes".into())].into()),
Field::new("wind_transport_white",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"White ash transported by wind (total mass)".into())].into()),
Field::new("wind_transport_white_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"White ash transported by wind per unit area over white ash hillslopes".into())].into()),
Field::new("water_transport",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"Ash transported by water (total mass)".into())].into()),
Field::new("water_transport_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"Ash transported by water per unit area".into())].into()),
Field::new("water_transport_black",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"Black ash transported by water (total mass)".into())].into()),
Field::new("water_transport_black_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"Black ash transported by water per unit area over black ash hillslopes".into())].into()),
Field::new("water_transport_white",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"White ash transported by water (total mass)".into())].into()),
Field::new("water_transport_white_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"White ash transported by water per unit area over white ash hillslopes".into())].into()),
Field::new("ash_transport",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"Total ash transported (wind + water)".into())].into()),
Field::new("ash_transport_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"Total ash transported per unit area".into())].into()),
Field::new("ash_transport_black",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"Black ash transported by wind + water (total mass)".into())].into()),
Field::new("ash_transport_black_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"Black ash transported per unit area over black ash hillslopes".into())].into()),
Field::new("ash_transport_white",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"White ash transported by wind + water (total mass)".into())].into()),
Field::new("ash_transport_white_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"White ash transported per unit area over white ash hillslopes".into())].into()),
Field::new("transportable_ash",DataType::Float64,true).with_metadata([("units".into(),"tonne".into()), ("description".into(),"Ash mass still available for transport".into())].into()),
Field::new("transportable_ash_per_ha",DataType::Float64,true).with_metadata([("units".into(),"tonne/ha".into()), ("description".into(),"Ash mass still available for transport per unit area".into())].into()),
Field::new("ash_vol_conc",DataType::Float64,true).with_metadata([("units".into(),"m^3/m^3".into()), ("description".into(),"Ash volumetric concentration (solids volume divided by runoff volume)".into())].into()),
Field::new("sed+ash_vol_conc",DataType::Float64,true).with_metadata([("units".into(),"m^3/m^3".into()), ("description".into(),"Sediment + ash volumetric concentration (total solids volume divided by runoff volume)".into())].into()),
Field::new("ash_black_pct_by_vol",DataType::Float64,true).with_metadata([("units".into(),"percent".into()), ("description".into(),"Fraction of ash solids volume that is black ash (percent of total ash volume)".into())].into()),
];
    let mut schema = schema_with_version(Schema::new(fields), version);
    if let Some(pandas) = pandas {
        let mut meta = schema.metadata().clone();
        meta.insert("pandas".into(), pandas.into());
        schema = schema.with_metadata(meta);
    }
    schema
}
