[package]
name = "raster_characteristics_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
gdal = { version = "0.16", features = ["bindgen"]}
proj = "0.27.2"
raster = { path = "../raster" }
